# Generated by Django 5.2.12 on 2026-04-18 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='название')),
                ('artist', models.CharField(max_length=200, verbose_name='исполнитель')),
                ('lyrics', models.TextField(verbose_name='текст песни')),
                ('translate', models.TextField(verbose_name='перевод песни')),
                ('level', models.CharField(choices=[('A1', 'Начальный (A1)'), ('A2', 'Элементарный (A2)'), ('B1', 'Средний (B1)'), ('B2', 'Выше среднего (B2)'), ('C1', 'Продвинутый (C1)')], default='Начальный', max_length=2, verbose_name='уровень')),
                ('vocabulary', models.TextField(default='{}', help_text='Формат JSON: {"word": "translation", "phrase": "translation"}', verbose_name='словарь песни')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата добавления')),
            ],
            options={
                'verbose_name': 'song',
                'verbose_name_plural': 'songs',
                'ordering': ['-created_at'],
            },
        ),
    ]
