# Generated by Django 5.2.12 on 2026-04-18 17:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='level',
            field=models.CharField(choices=[('A1', 'Начальный (A1)'), ('A2', 'Элементарный (A2)'), ('B1', 'Средний (B1)'), ('B2', 'Выше среднего (B2)'), ('C1', 'Продвинутый (C1)')], default='A1', max_length=2, verbose_name='уровень'),
        ),
        migrations.CreateModel(
            name='UserWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=200, verbose_name='слово')),
                ('translation', models.CharField(max_length=500, verbose_name='перевод')),
                ('context', models.TextField(blank=True, verbose_name='предложение с этим словом')),
                ('song_title', models.CharField(blank=True, max_length=200, verbose_name='название песни')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата добавления')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'слово пользователя',
                'verbose_name_plural': 'слова пользователя',
                'unique_together': {('user', 'word')},
            },
        ),
    ]
